### ISSUE TITLE
Feature Request: Foundry Support

### ISSUE THREAD

**Issue by alexroan** [TheBojda/zktree#5]
Hey, thanks for putting together such a useful resource! I found this really easy to import and spin up my own ZK-enabled repo using Hardhat.

Do you have any plans to make this more Foundry-friendly? I'd love to help out if so!

**Comment by TheBojda** [comment]
Hi! I do not really know Foundry, but the library itself is (theoretically) framework independent.

**Comment by alexroan** [comment]
So Foundry enables tests to be written and executed using Solidity, rather than having to switch language context.

The blocker I hit whilst trying to import this was setting up the tests as you have in [ZKTree Vote](https://github.com/TheBojda/zktree-vote). Specifically, porting the [deployment of the `mimcsponge` contract](https://github.com/TheBojda/zktree-vote/blob/main/test/zktree_vote_test.ts#L18) over. This functionality is imported from `circomlibjs` anyway, so perhaps this isn't the correct place to discuss it, but I'm wondering if you know of ways that steps like this can be done using `circom` or `circomlib` instead maybe?

I'm relatively new to the ZK world so any info would be greatly appreciated! 🙏

**Comment by TheBojda** [comment]
Testing with solidity here is meaningless. You can use the generated Verifier to test the Verifier, but testing something with itself is meaningless. :)

I'm testing the generated Verifier with circomlibjs' JS implementation in my tests.
